### ISSUE TITLE
How to fix pagination UI issue on posts page

### ISSUE THREAD

**Issue by qadeesz** [codecourse/posty-traversy-media#5]
![image](https://user-images.githubusercontent.com/25366607/200903935-4b10fe5d-8d77-4267-a0c6-6e75644ca99e.png)

**Comment by codedByShoe** [comment]
@qadeesz
Go to the AppServiceProvider.php file in the providers directory and in the boot method add Paginator::useTailwind();

It will not look exactly like the one in the tutorial but it will fix the UI issues with the large svg. Hope this helps

**Comment by qadeesz** [comment]
@Ashoemaker-tech  thanks
